#v0.37.3

services:
  metabase:
    image: ghcr.io/arkadiuminc/metabase
    container_name: metabase
    networks:
      - iuhkart-network
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/
    ports:
      - 3000:3000
    restart: always

  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: iuhkart-metabase-cloudflare
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiYjEyNTc2NjEwYTQyYzVmM2JmZTZlZThhZjE1MjIwM2EiLCJ0IjoiNWZiM2UzOGItNjM0YS00MGYwLTgzOTctMzEzMjZhODkwYWE5IiwicyI6Ik1UZGlaVEl3WW1FdFpEVmhZeTAwTTJWaUxUa3dOVEF0TmpjNVpqWXdPVGRqWkdNMCJ9
    networks:
      - iuhkart-network
    depends_on:
      metabase:
        condition: service_started

networks:
  iuhkart-network:
    name: iuhkart-network
    external: true