networks:
    iuhkart-network:
        name: iuhkart-network
        external: true

services:
    storage-stream:
        image: postgres:16-alpine
        container_name: storage-stream
        networks:
            - iuhkart-network
        ports:
            - 15361:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
            - ./data/storage_stream:/data/postgres
            - ./jobs/postgres.sql:/docker-entrypoint-initdb.d/postgres.sql:ro
        restart: always
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres"]
            interval: 5s
            retries: 5
    
    flink-jobmanager:
        container_name: flink-jobmanager
        # build: configs/flink-1.18.1
        image: qxnam/flink-etl:latest
        ports:
            - "28081:8081"
        environment:
            - |
                FLINK_PROPERTIES=
                jobmanager.rpc.address: flink-jobmanager
        command: jobmanager
        networks:
            - iuhkart-network
        volumes:
            - ./jobs:/opt/flink/jobs
        restart: always
    
    flink-taskmanager:
        container_name: flink-taskmanager
        # build: configs/flink-1.18.1
        image: qxnam/flink-etl:latest
        depends_on:
            - flink-jobmanager
        command: taskmanager
        scale: 1
        environment:
            - |
                FLINK_PROPERTIES=
                jobmanager.rpc.address: flink-jobmanager
                taskmanager.numberOfTaskSlots: 8
        networks:
            - iuhkart-network
        volumes:
            - ./jobs:/opt/flink/jobs
        restart: always

